spring:
  r2dbc:
#    url: r2dbc:h2:mem:///default
    url: r2dbc:h2:file:///./data/demo
    username: sa
    password:


  flyway:
#    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
    url: jdbc:h2:file:./data/demo
    baseline-on-migrate: true
    user: sa
    password:

h2-server:
  port: 8081