#!/bin/sh
set -x
set -e
# From gist at https://gist.github.com/chadmaughan/5889802

# run the tests with the gradle wrapper
./gradlew checkstyleMain

# run find bugs check
./gradlew spotbugsMain

# store the last exit code in a variable
RESULT=$?

# return the './gradlew build' exit code
exit $RESULT
